### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by pussinmood** [PierreMarza/task_conditioned_adaptation#3] opened 2024-08-26 05:54 UTC
I tried to run 《Test on *faucet-close-v2-goal-observable*》 after 《Task embedding search on *faucet-close-v2-goal-observable*》，this issue showed :
RS:> Registering Arms Envs
RS:> Registering Biomechanics Envs
RS:> Registering Hand Envs
RS:> Registering Kitchen Envs
Using CUDA.
Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/run/eval.py", line 168, in <module>
    e = env_constructor(
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 87, in env_constructor
    e = FrozenEmbeddingWrapper(
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 249, in __init__
    proprio = self.get_proprio()
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 248, in <lambda>
    self.get_proprio = lambda: get_proprioception(self.unwrapped, suite)
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 335, in get_proprioception
    assert isinstance(env, gym.Env)
AssertionError
My metaworld==2.0.0

**Comment by pussinmood** [comment] 2024-08-26 06:02
Trying to do《Test on *assembly-v2-goal-observable*》 is the same issue like this.

**Comment by PierreMarza** [comment] 2024-08-26 07:36
I cannot reproduce this error. I have 3 questions:
1. Do you also get the same error when running _eval.py_ on **known tasks** from _MetaWorld_?
2. Are you able to run _eval.py_ for tasks that are not from _MetaWorld_ (e.g. known tasks from _DMC_ or _Adroit_)?
3. How have you installed _metaworld_?

**Comment by pussinmood** [comment] 2024-08-27 05:10
1.yes,i tried other known tasks from metaworld,same issues.
2.i can run eval.py for tasks not from metaworld
3.i cloned metaworld from https://github.com/Farama-Foundation/Metaworld ,and pip install -e. metaworld==2.0.0
sorry to bother you with these numb issues.....

**Comment by pussinmood** [comment] 2024-08-27 05:33
i also tried metaworld==0.1.0，different issue appeared：
Traceback (most recent call last):
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_env.py", line 110, in reset
    return self.env.unwrapped.reset_model(seed=seed)
TypeError: reset_model() got an unexpected keyword argument 'seed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/run/eval.py", line 174, in <module>
    paths = sample_paths(
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/utils/utils.py", line 218, in sample_paths
    return do_rollout(**input_dict)
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/utils/utils.py", line 145, in do_rollout
    o = env.reset()
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_env.py", line 114, in reset
    return self.env.reset()
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 325, in reset
    return super().reset()
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 169, in observation
    return self.get_image()
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/gym/gym_wrapper.py", line 155, in get_image
    img = self.sim.render(
  File "mjsim.pyx", line 153, in mujoco_py.cymj.MjSim.render
  File "wrappers.pxi", line 1069, in mujoco_py.cymj.PyMjModel.camera_name2id
ValueError: No "camera" with name top_cap2 exists. Available "camera" names = ('topview', 'corner', 'corner2', 'corner3', 'behindGripper', 'gripperPOV').

**Comment by PierreMarza** [comment] 2024-08-28 07:18
Hi, thank you for this additional information, and sorry to hear you are facing these issues... Have you followed all the installation guidelines? Have you had any trouble with some of them, or have you done additional installations? Also, in another issue (https://github.com/PierreMarza/task_conditioned_adaptation/issues/2), you updated your mujoco version, right? Have you done this after or before installing metaworld?

**Comment by pussinmood** [comment] 2024-08-28 13:31
Thanks again for your attention and guidence ，i followed your installation guidelines,but some issues appeared such as lackness of something ,i solved them with  
'''
sudo apt-get update
sudo apt-get install -y libx11-dev  
sudo apt-get install libglew-dev    
sudo apt-get install libegl1-mesa-dev
pip install cython==0.29.12(to avoid a issue)
'''
don't know why my mujoco==3.2.2,so i use 'pip install mujoco==2.3.5',i may did something wrong during the installation,so maybe i can solve this problem with rebuilding the environment ?
By the way,i'm a chinese ,so i'm using a cloud server without a global internet,it may cause some trouble during installation,i had to pip every single one of your environment.yml one by one.
When i use my laptop ,i  installed more properly,but same issue appear ,metaworld installation is after the main envs installation and two issues before. 
my situations now is metaworld‘s task can't be done through eval.py ,what is the metaworld's version you are using ? i will try  to install this env again to see the outcoming ,appreciate your kindness one more time~.~

**Comment by PierreMarza** [comment] 2024-08-29 12:10
The installation guidelines involve cloning the _eai_vc_ code repository. Have you tried installing _metaworld_ from their _third_party_ dependencies? If not, try the following,

```console
cd eai_vc
pip install -e ./third_party/metaworld
```

**Comment by pussinmood** [comment] 2024-08-30 01:27
i didn't ，thanks ，i will try this out～。～

**Comment by pussinmood** [comment] 2024-08-30 01:39
it looks like ok now ,just use 'export MUJOCO_GL=osmesa' to avoid issue  'mujoco.FatalError: gladLoadGL error'.
thank you very very much！you just made my day.

**Comment by PierreMarza** [comment] 2024-08-30 13:11
Great, I'm thus closing this issue. Feel free to reopen if needed!

**Closed as completed by PierreMarza** 2024-08-30 13:11 UTC
